Try to also support 32-bit platforms
Some of the inline IR code references missing functions causing
linking failures, such as "error: undefined reference to '__umodti3'".
Just use the code from 'core.int128' as a fallback.