Fix "error: undefined reference to '__multi3'" on 32-bit ARM
The 'sub' and 'neg' functions are also affected, because Clang
somehow generates multiplications in the LLVM IR for them.